2023-12-04 14:48:10.186076: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/mnt/local/cuda/lib64:/mnt/local/petsc/lib:/mnt/local/cuba/lib:/usr/lib64/cernlib/2006-g77/lib:/mnt/local/gromacs/lib64:/mnt/local/cuda/lib64:/mnt/local/petsc/lib:/mnt/local/cuba/lib:/usr/lib64/cernlib/2006-g77/lib:/mnt/local/gromacs/lib64
2023-12-04 14:48:10.186533: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
